matrix:
  include:
    - language: python
      python: 3.7
      install:
        - pip install -r requirementsPython.txt
#      script:
#        - python manage.py test
    - language: node_js
      node_js:
        - "12"
      install:
        - npm install
dist: trusty
env:
  - PORT=3005
  - TOKEN=DF3A2DEEB01F32C0C6B98DC810FB0D80
cache:
  directories:
    - node_modules
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
